apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nepa-ingress
  namespace: devops
  labels:
    kcert.dev/ingress: "managed"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - nepa.demo.agileguru.org
    secretName: nepa-alacritysys-com
  rules:
  - host: nepa.demo.agileguru.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: client-service
            port: 
                number: 8888
      - path: /server
        pathType: Prefix
        backend:
          service: 
            name: server-service
            port: 
                number: 8080