---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-add-ons-http
  namespace: devops
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keda-add-ons-http
    repoURL: https://kedacore.github.io/charts
    targetRevision: 0.6.0
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true