---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-scanner
  namespace: devops
spec:
  destination:
    namespace: trivy-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: trivy.ignoreUnfixed
          value: "true"
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.18.4
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true