apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: multi-container-example
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{client: [server]}"
    spec:
      containers:
      - image: agileguru/graalvmcloudnativeclient:main
        name: client
        ports:
        - name: http1
          containerPort: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      - image: agileguru/graalvmcloudnativeserver:main
        name: server
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi