apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-overlay

namespace: dev

resources:
- ../../base/namespaces/dev
- ../../base/server
- ../../base/client
- ../../base/nepa-ingress


# patchesStrategicMerge:
#   - server-override.yaml